### ISSUE TITLE
Links for Theorem Provers and Program Synthesis are broken

### ISSUE THREAD

**Issue by Chillee** [cs6110/2017sp-web#1]
Seems like it's prepending `cs.cornell.edu`, so you get a link `https://www.cs.cornell.edu/github.com/cs6110/2017sp-web/blob/master/src/lectures/leandemo.md`, which isn't what you want.

**Comment by sampsyo** [comment]
Hmm; that's odd—the link works for me here. The source that my browser gets contains:

```
<a href="https:/github.com/cs6110/2017sp-web/blob/master/src/lectures/leandemo.md">notes</a>
```

which seems right? Any chance something could be going on with your browser?

**Comment by Chillee** [comment]
Sorry, I filed it in the wrong year. The links for the 2018 version are broken, not the 2017 ones.

https://www.cs.cornell.edu/courses/cs6110/2018sp/schedule.html
